# Generated by Django 5.2.3 on 2025-06-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='cases', to='cases.service'),
        ),
        migrations.AddField(
            model_name='case',
            name='stacks',
            field=models.ManyToManyField(blank=True, related_name='cases', to='cases.stack'),
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cases', to='cases.tag'),
        ),
    ]
